# Stage 1: Build
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the Next.js app
RUN npm run build

# Stage 2: Production
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy only the built app from the builder stage
COPY --from=builder /app ./

# Install only production dependencies
RUN npm install --production --frozen-lockfile

# Expose the port that Next.js listens on
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "start"]
